import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { Tag, Plus, Trash2, MoreHorizontal, Edit2, ToggleLeft, ToggleRight, CheckCircle2, XCircle } from 'lucide-react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@/components/ui/dialog';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { useToast } from '@/hooks/use-toast';
import { AdminTableError, AdminTableLoading } from '@/components/admin/AdminPageState';

interface Coupon { id:number; code:string; type:'percentage'|'fixed'; value:number; minOrder:number|null; maxUses:number|null; usedCount:number; isActive:number; expiresAt:string|null; createdAt:string; }
async function apiFetch<T>(path:string, init?:RequestInit):Promise<T>{ const res=await fetch(path,{credentials:'include',...init}); if(!res.ok){let msg=`Request failed (${res.status})`;try{msg=(await res.json()).error??msg}catch{} throw new Error(msg)} if(res.status===204)return undefined as T; return res.json() as Promise<T>; }
type CouponForm={code:string;type:'percentage'|'fixed';value:string;minOrder:string;maxUses:string;expiresAt:string};
const EMPTY_FORM:CouponForm={code:'',type:'percentage',value:'',minOrder:'',maxUses:'',expiresAt:''};

export default function Coupons(){
 const qc=useQueryClient(); const {toast}=useToast(); const [dialogOpen,setDialogOpen]=useState(false); const [editing,setEditing]=useState<Coupon|null>(null); const [form,setForm]=useState(EMPTY_FORM);
 const {data:coupons=[],isLoading,isError,refetch}=useQuery<Coupon[]>({queryKey:['coupons'],queryFn:()=>apiFetch('/api/coupons')});
 const createMut=useMutation({mutationFn:(body:object)=>apiFetch('/api/coupons',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),onSuccess:()=>{qc.invalidateQueries({queryKey:['coupons']});toast({title:'Coupon created'});setDialogOpen(false)},onError:(e:any)=>toast({title:'Error',description:e.message,variant:'destructive'})});
 const updateMut=useMutation({mutationFn:({id,body}:{id:number;body:object})=>apiFetch(`/api/coupons/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),onSuccess:()=>{qc.invalidateQueries({queryKey:['coupons']});toast({title:'Coupon updated'});setDialogOpen(false)},onError:(e:any)=>toast({title:'Error',description:e.message,variant:'destructive'})});
 const deleteMut=useMutation({mutationFn:(id:number)=>apiFetch(`/api/coupons/${id}`,{method:'DELETE'}),onSuccess:()=>{qc.invalidateQueries({queryKey:['coupons']});toast({title:'Coupon deleted'})},onError:(e:any)=>toast({title:'Error',description:e.message,variant:'destructive'})});
 function openCreate(){setEditing(null);setForm(EMPTY_FORM);setDialogOpen(true)}
 function openEdit(c:Coupon){setEditing(c);setForm({code:c.code,type:c.type,value:String(c.value),minOrder:c.minOrder!=null?String(c.minOrder):'',maxUses:c.maxUses!=null?String(c.maxUses):'',expiresAt:c.expiresAt?c.expiresAt.slice(0,10):''});setDialogOpen(true)}
 function handleSubmit(e:React.FormEvent){e.preventDefault();const body={code:form.code.toUpperCase().trim(),type:form.type,value:parseFloat(form.value),minOrder:form.minOrder?parseFloat(form.minOrder):null,maxUses:form.maxUses?parseInt(form.maxUses):null,expiresAt:form.expiresAt||null};if(!body.code||isNaN(body.value))return;editing?updateMut.mutate({id:editing.id,body}):createMut.mutate(body)}
 function toggleActive(c:Coupon){updateMut.mutate({id:c.id,body:{isActive:c.isActive?0:1}})}
 function handleDelete(id:number){if(confirm('Delete this coupon permanently?'))deleteMut.mutate(id)}
 const inputClass='h-11 rounded-xl border border-slate-200 bg-white px-3 text-sm shadow-none focus-visible:ring-4 focus-visible:ring-violet-100 focus-visible:border-violet-400';
 const labelClass='text-[10px] uppercase tracking-wider font-black text-slate-500';
 return <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4">
  <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-3xl font-black text-slate-950">Coupons</h1><p className="mt-1 text-sm text-slate-500">Create and manage discount codes for customers.</p></div><Button onClick={openCreate} className="h-11 rounded-xl bg-slate-950 px-5 font-bold text-white gap-2"><Plus className="w-4 h-4"/>New Coupon</Button></div>
  <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">{[{label:'Total Coupons',value:coupons.length},{label:'Active',value:coupons.filter(c=>c.isActive).length},{label:'Total Uses',value:coupons.reduce((a,c)=>a+c.usedCount,0)},{label:'Expired',value:coupons.filter(c=>c.expiresAt&&new Date(c.expiresAt)<new Date()).length}].map(s=><Card key={s.label} className="rounded-2xl border border-slate-200 bg-white shadow-sm"><CardContent className="p-5"><p className="text-[10px] uppercase tracking-wider text-slate-500 font-bold">{s.label}</p><p className="mt-2 text-2xl font-black text-slate-950">{s.value}</p></CardContent></Card>)}</div>
  <Card className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><CardContent className="p-0"><Table className="admin-table"><TableHeader className="bg-slate-50"><TableRow><TableHead>Code</TableHead><TableHead>Type / Value</TableHead><TableHead>Min. Order</TableHead><TableHead>Usage</TableHead><TableHead>Expires</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{isLoading?<AdminTableLoading columns={7}/>:isError?<AdminTableError columns={7} onRetry={()=>void refetch()}/>:coupons.length===0?<TableRow><TableCell colSpan={7} className="text-center py-12"><Tag className="w-8 h-8 text-slate-300 mx-auto mb-3"/><p className="text-slate-500">No coupons yet. Create your first discount code.</p></TableCell></TableRow>:coupons.map(c=>{const isExpired=c.expiresAt&&new Date(c.expiresAt)<new Date();const isExhausted=c.maxUses!=null&&c.usedCount>=c.maxUses;return <TableRow key={c.id}><TableCell className="font-mono font-bold">{c.code}</TableCell><TableCell>{c.type==='percentage'?`${c.value}% off`:`Rs. ${c.value.toLocaleString('en-IN')} off`}</TableCell><TableCell>{c.minOrder?`Rs. ${c.minOrder.toLocaleString('en-IN')}`:'—'}</TableCell><TableCell>{c.usedCount}{c.maxUses!=null?` / ${c.maxUses}`:''}</TableCell><TableCell>{c.expiresAt?<span className={isExpired?'text-red-600 font-semibold':''}>{new Date(c.expiresAt).toLocaleDateString('en-GB')}</span>:'—'}</TableCell><TableCell>{isExpired||isExhausted?<span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-bold">{isExpired?'Expired':'Exhausted'}</span>:c.isActive?<span className="inline-flex items-center gap-1 rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-bold text-emerald-700"><CheckCircle2 className="w-3 h-3"/>Active</span>:<span className="inline-flex items-center gap-1 rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-bold"><XCircle className="w-3 h-3"/>Inactive</span>}</TableCell><TableCell className="text-right"><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" className="h-9 w-9 rounded-lg p-0"><MoreHorizontal className="h-4 w-4"/></Button></DropdownMenuTrigger><DropdownMenuContent align="end" className="rounded-xl"><DropdownMenuItem onClick={()=>openEdit(c)}><Edit2 className="mr-2 h-4 w-4"/>Edit</DropdownMenuItem><DropdownMenuItem onClick={()=>toggleActive(c)}>{c.isActive?<ToggleLeft className="mr-2 h-4 w-4"/>:<ToggleRight className="mr-2 h-4 w-4"/>}{c.isActive?'Deactivate':'Activate'}</DropdownMenuItem><DropdownMenuItem onClick={()=>handleDelete(c.id)} className="text-red-600"><Trash2 className="mr-2 h-4 w-4"/>Delete</DropdownMenuItem></DropdownMenuContent></DropdownMenu></TableCell></TableRow>})}</TableBody></Table></CardContent></Card>
  <Dialog open={dialogOpen} onOpenChange={setDialogOpen}><DialogContent className="overflow-hidden rounded-2xl border border-slate-200 bg-white p-0 sm:max-w-[560px]"><div className="border-b border-slate-100 bg-white px-6 py-5"><DialogHeader><DialogTitle className="text-xl font-black text-slate-950">{editing?'Edit Coupon':'New Coupon'}</DialogTitle></DialogHeader><p className="mt-1 text-sm text-slate-500">Set the discount, limits and optional expiry date.</p></div><form onSubmit={handleSubmit} className="space-y-5 p-6"><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label className={labelClass}>Coupon Code *</Label><Input value={form.code} onChange={e=>setForm(f=>({...f,code:e.target.value.toUpperCase()}))} placeholder="SAVE20" className={inputClass} required/></div><div className="space-y-2"><Label className={labelClass}>Type *</Label><Select value={form.type} onValueChange={(v:any)=>setForm(f=>({...f,type:v}))}><SelectTrigger className={inputClass}><SelectValue/></SelectTrigger><SelectContent className="rounded-xl"><SelectItem value="percentage">Percentage (%)</SelectItem><SelectItem value="fixed">Fixed Amount (Rs.)</SelectItem></SelectContent></Select></div></div><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label className={labelClass}>{form.type==='percentage'?'Discount (%)':'Discount Amount (Rs.)'} *</Label><Input type="number" value={form.value} onChange={e=>setForm(f=>({...f,value:e.target.value}))} placeholder={form.type==='percentage'?'20':'500'} min="0" step={form.type==='percentage'?'0.1':'1'} className={inputClass} required/></div><div className="space-y-2"><Label className={labelClass}>Min. Order Value (Rs.)</Label><Input type="number" value={form.minOrder} onChange={e=>setForm(f=>({...f,minOrder:e.target.value}))} placeholder="Optional" min="0" className={inputClass}/></div></div><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label className={labelClass}>Max Uses</Label><Input type="number" value={form.maxUses} onChange={e=>setForm(f=>({...f,maxUses:e.target.value}))} placeholder="Unlimited" min="1" className={inputClass}/></div><div className="space-y-2"><Label className={labelClass}>Expiry Date</Label><Input type="date" value={form.expiresAt} onChange={e=>setForm(f=>({...f,expiresAt:e.target.value}))} className={inputClass}/></div></div><DialogFooter className="gap-2 border-t border-slate-100 pt-5"><Button type="button" variant="outline" onClick={()=>setDialogOpen(false)} className="h-11 rounded-xl px-5 font-bold">Cancel</Button><Button type="submit" disabled={createMut.isPending||updateMut.isPending} className="h-11 rounded-xl bg-violet-950 px-7 font-bold text-white">{createMut.isPending||updateMut.isPending?'Saving...':editing?'Save Changes':'Create Coupon'}</Button></DialogFooter></form></DialogContent></Dialog>
 </div>
}
