import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, Boxes, CheckCircle2, Factory, Loader2, PackageSearch, Plus, RefreshCw, RotateCcw, Search, Trash2 } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

const currentMonth=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Colombo",year:"numeric",month:"2-digit"}).format(new Date());
type Material={id:number;name:string;quantity:number;unit:string;low_stock_threshold:number};
type RecordRow={id:number;staff_name?:string;material_name:string;unit:string;reference?:string;used_quantity:number;waste_quantity:number;note?:string;usage_date:string;created_at:string};
const emptyForm={inventoryItemId:"",reference:"",usedQuantity:"",wasteQuantity:"",note:""};

export default function ProductionUsage(){
 const {toast}=useToast(); const [month,setMonth]=useState(currentMonth()); const [role,setRole]=useState(""); const [materials,setMaterials]=useState<Material[]>([]); const [records,setRecords]=useState<RecordRow[]>([]); const [saving,setSaving]=useState(false); const [loading,setLoading]=useState(true); const [search,setSearch]=useState(""); const [form,setForm]=useState(emptyForm);
 const request=async(url:string,options?:RequestInit)=>{const response=await fetch(url,{credentials:"include",cache:"no-store",...options,headers:options?.body?{"Content-Type":"application/json"}:undefined});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||"Request failed");return body;};
 const load=async()=>{setLoading(true);try{const[m,u]=await Promise.all([request("/api/admin/production-usage/materials"),request(`/api/admin/production-usage?month=${encodeURIComponent(month)}`)]);setMaterials(m);setRecords(u.records||[]);setRole(u.role);}catch(e:any){toast({title:"Production usage could not load",description:e.message,variant:"destructive"});}finally{setLoading(false);}};
 useEffect(()=>{void load();},[month]);
 const selected=materials.find(m=>String(m.id)===form.inventoryItemId); const used=Math.max(0,Math.floor(Number(form.usedQuantity)||0)); const waste=Math.max(0,Math.floor(Number(form.wasteQuantity)||0)); const total=used+waste; const remaining=selected?selected.quantity-total:0; const insufficient=Boolean(selected&&total>selected.quantity);
 const totals=useMemo(()=>records.reduce((a,r)=>({used:a.used+Number(r.used_quantity),waste:a.waste+Number(r.waste_quantity),entries:a.entries+1}),{used:0,waste:0,entries:0}),[records]); const wasteRate=totals.used+totals.waste?(totals.waste/(totals.used+totals.waste))*100:0;
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return records.filter(r=>!q||[r.material_name,r.reference,r.note,r.staff_name].some(v=>String(v||"").toLowerCase().includes(q)));},[records,search]); const lowStock=materials.filter(m=>m.quantity<=m.low_stock_threshold);
 const save=async()=>{if(insufficient)return;setSaving(true);try{const result=await request("/api/admin/production-usage",{method:"POST",body:JSON.stringify(form)});toast({title:"Usage recorded",description:`Remaining stock: ${result.remaining_stock} ${selected?.unit||""}`});setForm(emptyForm);await load();}catch(e:any){toast({title:"Could not save usage",description:e.message,variant:"destructive"});}finally{setSaving(false);}};
 const input="mt-1.5 h-12 w-full rounded-2xl border border-slate-200 bg-white px-4 text-sm font-semibold text-slate-800 outline-none transition placeholder:text-slate-300 focus:border-violet-400 focus:ring-4 focus:ring-violet-100";
 const cards=[{label:"Entries",value:totals.entries,Icon:Boxes,color:"text-violet-500"},{label:"Used quantity",value:totals.used,Icon:CheckCircle2,color:"text-emerald-500"},{label:"Waste quantity",value:totals.waste,Icon:Trash2,color:"text-amber-500"},{label:"Waste rate",value:`${wasteRate.toFixed(1)}%`,Icon:AlertTriangle,color:wasteRate>10?"text-rose-500":"text-slate-500"}];
 return <div className="space-y-6 pb-10">
  <header className="rounded-[28px] border border-violet-100 bg-gradient-to-br from-white via-violet-50/70 to-amber-50/60 p-5 shadow-sm sm:p-7"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-start gap-4"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-slate-950 text-white shadow-lg"><Factory size={22}/></div><div><span className="text-[10px] font-black uppercase tracking-[.2em] text-violet-600">Studio workflow</span><h1 className="mt-1 text-2xl font-black tracking-tight text-slate-950 sm:text-3xl">Production Usage</h1><p className="mt-1 max-w-2xl text-sm leading-6 text-slate-500">Record material use and waste clearly. Stock is deducted safely in one transaction.</p></div></div><div className="flex gap-2"><input aria-label="Usage month" type="month" value={month} onChange={e=>setMonth(e.target.value)} className="h-11 rounded-2xl border border-white bg-white/90 px-3 text-sm font-bold shadow-sm outline-none"/><button aria-label="Refresh" onClick={()=>void load()} className="grid h-11 w-11 place-items-center rounded-2xl bg-white text-violet-700 shadow-sm"><RefreshCw size={17} className={loading?"animate-spin":""}/></button></div></div></header>
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(({label,value,Icon,color})=><div key={label} className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><span className="text-[10px] font-black uppercase tracking-[.14em] text-slate-400">{label}</span><Icon size={16} className={color}/></div><div className="mt-3 text-2xl font-black text-slate-900">{value}</div></div>)}</section>
  {lowStock.length>0&&<div className="flex gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-amber-900"><AlertTriangle className="shrink-0" size={18}/><div><b className="text-xs uppercase tracking-wide">Low stock attention</b><p className="mt-1 text-xs leading-5">{lowStock.map(m=>`${m.name}: ${m.quantity} ${m.unit}`).join(" · ")}</p></div></div>}
  <div className="grid gap-6 xl:grid-cols-[430px_minmax(0,1fr)]">
   <section className="h-fit rounded-[28px] border border-slate-200 bg-white p-5 shadow-sm xl:sticky xl:top-24 sm:p-6"><div className="flex items-center justify-between"><div><h2 className="text-lg font-black text-slate-900">Record material</h2><p className="mt-1 text-xs text-slate-500">Whole stock units only.</p></div><button onClick={()=>setForm(emptyForm)} aria-label="Clear form" className="grid h-9 w-9 place-items-center rounded-xl bg-slate-50 text-slate-500"><RotateCcw size={15}/></button></div><div className="mt-5 space-y-4">
    <label className="block text-[11px] font-black uppercase tracking-wide text-slate-500">Paper or material<select value={form.inventoryItemId} onChange={e=>setForm({...form,inventoryItemId:e.target.value})} className={input}><option value="">Choose stock item</option>{materials.map(m=><option key={m.id} value={m.id}>{m.name} — {m.quantity} {m.unit}</option>)}</select></label>
    {selected&&<div className="flex justify-between rounded-2xl bg-slate-50 px-4 py-3 text-xs"><span className="font-semibold text-slate-500">Available now</span><strong>{selected.quantity} {selected.unit}</strong></div>}
    <label className="block text-[11px] font-black uppercase tracking-wide text-slate-500">Order / invoice / project<input value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})} placeholder="Searchable reference" className={input}/></label>
    <div className="grid grid-cols-2 gap-3"><label className="text-[11px] font-black uppercase text-emerald-700">Used<input type="number" min="0" step="1" inputMode="numeric" value={form.usedQuantity} onChange={e=>setForm({...form,usedQuantity:e.target.value})} placeholder="0" className={input}/></label><label className="text-[11px] font-black uppercase text-amber-700">Waste<input type="number" min="0" step="1" inputMode="numeric" value={form.wasteQuantity} onChange={e=>setForm({...form,wasteQuantity:e.target.value})} placeholder="0" className={input}/></label></div>
    <label className="block text-[11px] font-black uppercase tracking-wide text-slate-500">Production note<textarea rows={3} value={form.note} onChange={e=>setForm({...form,note:e.target.value})} placeholder="Optional batch or operator note" className={`${input} h-auto min-h-24 resize-none py-3`}/></label>
    {selected&&total>0&&<div className={`rounded-2xl border p-4 text-xs leading-5 ${insufficient?"border-rose-200 bg-rose-50 text-rose-700":"border-violet-100 bg-violet-50 text-violet-800"}`}><b>{total} {selected.unit}</b> will be deducted. {insufficient?"Quantity exceeds available stock.":`Remaining: ${remaining} ${selected.unit}.`}</div>}
    <button onClick={()=>void save()} disabled={saving||!form.inventoryItemId||total<=0||insufficient} className="flex h-12 w-full items-center justify-center gap-2 rounded-2xl bg-slate-950 text-sm font-black text-white shadow-lg disabled:opacity-40">{saving?<Loader2 size={17} className="animate-spin"/>:<Plus size={17}/>} Save &amp; deduct stock</button>
   </div></section>
   <section className="min-w-0 rounded-[28px] border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-black text-slate-900">Usage history</h2><p className="mt-1 text-xs text-slate-500">{filtered.length} of {records.length} records</p></div><label className="relative sm:w-72"><Search className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400" size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search material or reference" className="h-11 w-full rounded-2xl border border-slate-200 bg-slate-50 pl-10 pr-4 text-sm font-semibold outline-none focus:ring-4 focus:ring-violet-100"/></label></div>
    <div className="mt-5 space-y-3">{loading?<div className="grid place-items-center py-20"><Loader2 className="animate-spin text-violet-600"/></div>:filtered.length?filtered.map(r=><article key={r.id} className="rounded-2xl border border-slate-200 p-4 hover:border-violet-200"><div className="flex flex-col gap-3 sm:flex-row sm:justify-between"><div className="min-w-0"><b className="block truncate text-slate-900">{r.material_name}</b><div className="mt-1 flex flex-wrap gap-2 text-[11px] font-semibold text-slate-400"><span>{String(r.usage_date).slice(0,10)}</span>{role==="owner"&&r.staff_name&&<span>· {r.staff_name}</span>}{r.reference&&<span className="rounded-full bg-violet-50 px-2 text-violet-700">{r.reference}</span>}</div></div><div className="flex shrink-0 gap-2"><span className="rounded-xl bg-emerald-50 px-3 py-2 text-xs font-black text-emerald-700">Used {r.used_quantity} {r.unit}</span><span className="rounded-xl bg-amber-50 px-3 py-2 text-xs font-black text-amber-700">Waste {r.waste_quantity} {r.unit}</span></div></div>{r.note&&<p className="mt-3 rounded-xl bg-slate-50 px-3 py-2 text-xs text-slate-600">{r.note}</p>}</article>):<div className="grid place-items-center py-20 text-center"><PackageSearch className="text-slate-300" size={34}/><p className="mt-3 text-sm font-bold text-slate-500">No matching usage records</p></div>}</div>
   </section>
  </div>
 </div>;
}
