import { useEffect,useRef,useState } from "react";
import { useParams } from "wouter";
import { CheckCircle2,FileSignature,Loader2,RotateCcw,ShieldCheck } from "lucide-react";

export default function ClientAgreement(){
 const{token}=useParams<{token:string}>();const[a,setA]=useState<any>(null),[error,setError]=useState(""),[sending,setSending]=useState(false),[form,setForm]=useState({signerName:"",nicNumber:"",phone:"",email:"",consent:false});
 const canvas=useRef<HTMLCanvasElement>(null),drawing=useRef(false),[hasInk,setHasInk]=useState(false);
 useEffect(()=>{fetch(`/api/client-agreements/${encodeURIComponent(token||"")}`,{cache:"no-store"}).then(async r=>{const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||"Agreement not found");return b}).then(setA).catch(e=>setError(e.message))},[token]);
 const pos=(e:any)=>{const c=canvas.current!,r=c.getBoundingClientRect(),p=e.touches?.[0]||e;return{x:(p.clientX-r.left)*(c.width/r.width),y:(p.clientY-r.top)*(c.height/r.height)}};
 const start=(e:any)=>{e.preventDefault();drawing.current=true;const p=pos(e),x=canvas.current!.getContext("2d")!;x.beginPath();x.moveTo(p.x,p.y)};
 const move=(e:any)=>{if(!drawing.current)return;e.preventDefault();const p=pos(e),x=canvas.current!.getContext("2d")!;x.lineWidth=3;x.lineCap="round";x.strokeStyle="#111827";x.lineTo(p.x,p.y);x.stroke();setHasInk(true)};
 const stop=()=>{drawing.current=false};const clear=()=>{const c=canvas.current!,x=c.getContext("2d")!;x.clearRect(0,0,c.width,c.height);setHasInk(false)};
 const sign=async()=>{if(!form.consent||!hasInk){setError("Please accept the agreement and add your signature.");return}setSending(true);setError("");try{const blob=await new Promise<Blob|null>(r=>canvas.current!.toBlob(r,"image/png"));if(!blob)throw new Error("Could not capture signature");const d=new FormData();d.append("signature",blob,"signature.png");d.append("signerName",form.signerName);d.append("nicNumber",form.nicNumber);d.append("phone",form.phone);d.append("email",form.email);d.append("consent","true");const r=await fetch(`/api/client-agreements/${encodeURIComponent(token||"")}/sign`,{method:"POST",body:d});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||"Could not sign agreement");setA((x:any)=>({...x,status:"signed",signed_at:b.signedAt}));}catch(e){setError(e instanceof Error?e.message:"Could not sign agreement")}finally{setSending(false)}};
 if(error&&!a)return <main className="grid min-h-screen place-items-center bg-slate-50 p-6"><div className="max-w-md rounded-3xl bg-white p-8 text-center shadow"><FileSignature className="mx-auto text-red-500"/><h1 className="mt-3 text-xl font-black">Agreement unavailable</h1><p className="mt-2 text-sm text-slate-500">{error}</p></div></main>;
 if(!a)return <main className="grid min-h-screen place-items-center"><Loader2 className="animate-spin"/></main>;
 if(a.status==="signed")return <main className="grid min-h-screen place-items-center bg-slate-50 p-6"><div className="max-w-lg rounded-3xl bg-white p-9 text-center shadow"><CheckCircle2 className="mx-auto text-emerald-600" size={52}/><h1 className="mt-4 text-2xl font-black">Agreement signed successfully</h1><p className="mt-2 text-slate-500">Thank you. The signed document and audit record are securely stored.</p><p className="mt-4 font-mono text-xs text-slate-400">Document: {a.document_hash}</p></div></main>;
 return <main className="min-h-screen bg-slate-50 px-4 py-8"><article className="mx-auto max-w-3xl overflow-hidden rounded-3xl bg-white shadow-xl"><header className="bg-slate-950 p-7 text-white"><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[.18em] text-pink-400"><ShieldCheck size={17}/>{a.brand_name}{a.operator_name && a.operator_name !== a.brand_name ? ` · Operated by ${a.operator_name}` : ""}</div><h1 className="mt-3 text-3xl font-black">{a.title}</h1><p className="mt-2 text-sm text-slate-300">For {a.client_name_snapshot}{a.client_business_snapshot?` · ${a.client_business_snapshot}`:""}</p></header>
 <section className="p-6 sm:p-8"><div className="whitespace-pre-wrap rounded-2xl border border-slate-200 bg-slate-50 p-5 text-sm leading-7 text-slate-700">{a.agreement_text}</div><div className="mt-3 text-[11px] text-slate-400">Document fingerprint: <span className="break-all font-mono">{a.document_hash}</span></div>
 <h2 className="mt-8 text-lg font-black">Sign this agreement</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Full legal name" value={form.signerName} onChange={v=>setForm({...form,signerName:v})}/><Field label="NIC / ID number" value={form.nicNumber} onChange={v=>setForm({...form,nicNumber:v})}/><Field label="Phone" value={form.phone} onChange={v=>setForm({...form,phone:v})}/><Field label="Email (optional)" value={form.email} onChange={v=>setForm({...form,email:v})}/></div>
 <div className="mt-5 flex items-center justify-between"><label className="text-sm font-bold">Electronic signature</label><button onClick={clear} className="flex items-center gap-1 text-xs font-bold text-slate-500"><RotateCcw size={14}/>Clear</button></div><canvas ref={canvas} width={900} height={250} onMouseDown={start} onMouseMove={move} onMouseUp={stop} onMouseLeave={stop} onTouchStart={start} onTouchMove={move} onTouchEnd={stop} className="mt-2 h-40 w-full touch-none rounded-xl border-2 border-dashed border-slate-300 bg-white"/>
 <label className="mt-5 flex items-start gap-3 rounded-xl bg-pink-50 p-4 text-sm"><input type="checkbox" className="mt-1" checked={form.consent} onChange={e=>setForm({...form,consent:e.target.checked})}/><span>I have read this agreement, agree to its terms, and intend my electronic signature to sign it.</span></label>{error&&<p className="mt-3 text-sm font-bold text-red-600">{error}</p>}<button disabled={sending||!form.signerName||!form.nicNumber||!form.phone} onClick={()=>void sign()} className="mt-5 w-full rounded-xl bg-slate-950 py-3.5 font-black text-white disabled:opacity-40">{sending?"Signing securely…":"Agree & Sign"}</button>
 <p className="mt-4 text-center text-xs text-slate-400">{a.brand_name === a.operator_name ? `Issued directly by ${a.operator_name}.` : `${a.brand_name} is operated by ${a.operator_name}.`} Signing date/time and security audit data are recorded with this document.</p></section></article></main>
}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="text-sm font-bold text-slate-700">{label}<input value={value} onChange={e=>onChange(e.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal outline-none focus:border-pink-400"/></label>}
