import { useEffect,useMemo,useState } from "react";
import { Factory,Loader2,Plus,RefreshCw,Trash2 } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
const currentMonth=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Colombo",year:"numeric",month:"2-digit"}).format(new Date());
type Material={id:number;name:string;quantity:number;unit:string;low_stock_threshold:number};
type RecordRow={id:number;staff_name?:string;material_name:string;unit:string;reference?:string;used_quantity:number;waste_quantity:number;note?:string;usage_date:string;created_at:string};
export default function ProductionUsage(){
 const {toast}=useToast();const [month,setMonth]=useState(currentMonth());const [role,setRole]=useState("");const [materials,setMaterials]=useState<Material[]>([]);const [records,setRecords]=useState<RecordRow[]>([]);const [saving,setSaving]=useState(false);const [loading,setLoading]=useState(true);
 const [form,setForm]=useState({inventoryItemId:"",reference:"",usedQuantity:"",wasteQuantity:"",note:""});
 const request=async(url:string,options?:RequestInit)=>{const r=await fetch(url,{credentials:"include",cache:"no-store",...options,headers:options?.body?{"Content-Type":"application/json"}:undefined});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||"Request failed");return b;};
 const load=async()=>{setLoading(true);try{const [m,u]=await Promise.all([request("/api/admin/production-usage/materials"),request(`/api/admin/production-usage?month=${encodeURIComponent(month)}`)]);setMaterials(m);setRecords(u.records||[]);setRole(u.role);}catch(e:any){toast({title:"Production usage could not load",description:e.message,variant:"destructive"});}finally{setLoading(false);}};
 useEffect(()=>{load();},[month]);
 const selected=materials.find(m=>String(m.id)===form.inventoryItemId);const total=Number(form.usedQuantity||0)+Number(form.wasteQuantity||0);
 const save=async()=>{setSaving(true);try{const result=await request("/api/admin/production-usage",{method:"POST",body:JSON.stringify(form)});toast({title:"Material usage saved",description:`Remaining stock: ${result.remaining_stock} ${selected?.unit||""}`});setForm({inventoryItemId:"",reference:"",usedQuantity:"",wasteQuantity:"",note:""});await load();}catch(e:any){toast({title:"Could not save usage",description:e.message,variant:"destructive"});}finally{setSaving(false);}};
 const totals=useMemo(()=>records.reduce((a,r)=>({used:a.used+Number(r.used_quantity),waste:a.waste+Number(r.waste_quantity)}),{used:0,waste:0}),[records]);
 return <div className="space-y-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><Factory className="text-pink-500"/><h1 className="text-2xl font-black">Production Usage</h1></div><p className="mt-1 text-sm text-gray-500">Record papers/materials used and wasted. Cost and profit details are never shown here.</p></div><div className="flex gap-2"><input type="month" value={month} onChange={e=>setMonth(e.target.value)} className="input-field w-auto"/><button onClick={load} className="rounded-xl border bg-white p-3"><RefreshCw size={16}/></button></div></div>
 <div className="grid gap-5 xl:grid-cols-[420px_1fr]"><div className="rounded-3xl border bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 text-lg font-black"><Plus size={18} className="text-pink-500"/>Add Used Material / Waste</h2><div className="mt-4 space-y-3"><label className="block text-xs font-bold text-gray-500">Paper or Material<select value={form.inventoryItemId} onChange={e=>setForm({...form,inventoryItemId:e.target.value})} className="input-field mt-1"><option value="">Select material</option>{materials.map(m=><option key={m.id} value={m.id}>{m.name} · Available {m.quantity} {m.unit}</option>)}</select></label><label className="block text-xs font-bold text-gray-500">Order / Invoice / Project reference<input value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})} placeholder="HAVESTORY order ID or invoice number" className="input-field mt-1"/></label><div className="grid grid-cols-2 gap-2"><label className="text-xs font-bold text-emerald-600">Used quantity<input type="number" min="0" step="1" value={form.usedQuantity} onChange={e=>setForm({...form,usedQuantity:e.target.value})} className="input-field mt-1"/></label><label className="text-xs font-bold text-orange-600">Waste quantity<input type="number" min="0" step="1" value={form.wasteQuantity} onChange={e=>setForm({...form,wasteQuantity:e.target.value})} className="input-field mt-1"/></label></div><textarea rows={3} value={form.note} onChange={e=>setForm({...form,note:e.target.value})} placeholder="Optional production note" className="input-field resize-none"/>{selected&&total>0&&<div className="rounded-xl bg-blue-50 p-3 text-xs text-blue-700"><b>{total} {selected.unit}</b> will be deducted from {selected.name}. Current stock: {selected.quantity} {selected.unit}.</div>}<button onClick={save} disabled={saving||!form.inventoryItemId||total<=0} className="flex w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-pink-500 to-purple-600 py-3 text-sm font-black text-white disabled:opacity-40">{saving?<Loader2 size={16} className="animate-spin"/>:<Plus size={16}/>}Save & Deduct Stock</button></div></div>
 <div className="rounded-3xl border bg-white p-5 shadow-sm"><div className="grid grid-cols-2 gap-3"><div className="rounded-2xl bg-emerald-50 p-4"><div className="text-xs font-bold text-emerald-600">TOTAL USED ENTRIES</div><div className="mt-1 text-2xl font-black">{totals.used}</div></div><div className="rounded-2xl bg-orange-50 p-4"><div className="text-xs font-bold text-orange-600">TOTAL WASTE</div><div className="mt-1 text-2xl font-black">{totals.waste}</div></div></div><div className="mt-4 space-y-2">{loading?<div className="flex justify-center py-16"><Loader2 className="animate-spin text-pink-500"/></div>:records.length?records.map(r=><div key={r.id} className="rounded-2xl border p-4"><div className="flex justify-between gap-3"><div><b>{r.material_name}</b><div className="text-xs text-gray-400">{String(r.usage_date).slice(0,10)}{role==="owner"&&r.staff_name?` · ${r.staff_name}`:""}{r.reference?` · ${r.reference}`:""}</div></div><div className="text-right text-xs"><div className="font-bold text-emerald-600">Used {r.used_quantity} {r.unit}</div><div className="font-bold text-orange-600">Waste {r.waste_quantity} {r.unit}</div></div></div>{r.note&&<div className="mt-2 rounded-lg bg-gray-50 p-2 text-xs text-gray-500">{r.note}</div>}</div>):<div className="py-16 text-center text-sm text-gray-400">No production usage records this month</div>}</div></div></div></div>;
}
