import { useEffect,useState } from "react";
import { useLocation,useParams } from "wouter";
import { ArrowLeft,CheckCircle2,Printer,ShieldCheck,XCircle } from "lucide-react";
import { A4PrintPortal,useA4Print } from "@/components/A4PrintPortal";

export default function StaffVerificationReport(){
 const {staffId}=useParams<{staffId:string}>();const[,setLocation]=useLocation();const id=Number(staffId);
 const[data,setData]=useState<any>(null),[staff,setStaff]=useState<any>(null),[note,setNote]=useState(""),[error,setError]=useState(""),[saving,setSaving]=useState(false);const{active:printActive,print:printA4}=useA4Print();
 const load=async()=>{try{const[v,t]=await Promise.all([fetch(`/api/admin/staff/${id}/verification`,{credentials:"include",cache:"no-store"}),fetch("/api/admin/team",{credentials:"include",cache:"no-store"})]);if(!v.ok)throw new Error("Could not load staff verification");const vd=await v.json(),people=t.ok?await t.json():[];setData(vd);setStaff((Array.isArray(people)?people:[]).find((x:any)=>x.id===id));setNote(vd.ownerNote||"");}catch(e){setError(e instanceof Error?e.message:"Could not load report")}};
 useEffect(()=>{void load()},[id]);
 const decide=async(decision:"approved"|"rejected")=>{setSaving(true);try{const r=await fetch(`/api/admin/staff/${id}/verification-decision`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({decision,note})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||"Could not save review");await load()}catch(e){setError(e instanceof Error?e.message:"Could not save review")}finally{setSaving(false)}};
 const image=(kind:string)=>`/api/admin/staff/${id}/verification/image/${kind}?v=${encodeURIComponent(data?.submittedAt||"")}`;
 if(error&&!data)return <div className="p-8 text-red-600">{error}</div>;if(!data||!staff)return <div className="p-8 text-slate-500">Loading secure staff report...</div>;
 const p=data.profile||{};
 const report=<article className="a4 pb-print-flow mx-auto max-w-[900px] rounded-3xl bg-white p-8 shadow-xl">
   <header className="border-b-2 border-slate-900 pb-5"><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[.2em] text-pink-600"><ShieldCheck size={18}/>PrintBloom · Operated by CodeArtix Technologies · Owner Confidential</div><h1 className="mt-2 text-3xl font-black">Staff Identity & Onboarding Report</h1><p className="mt-1 text-sm text-slate-500">{staff.name} · @{staff.username} · Generated {new Date().toLocaleString("en-LK")}</p><span className="mt-3 inline-block rounded-full bg-slate-100 px-3 py-1 text-xs font-black uppercase">{data.status||"not started"}</span></header>
   <section className="grid gap-5 border-b border-slate-200 py-6 sm:grid-cols-2"><Block title="Staff account" rows={[["Name",staff.name],["Username",staff.username],["Account active",staff.active?"Yes":"No"]]} /><Block title="Submitted identity" rows={[["Legal name",p.fullName],["NIC / ID",p.nicNumber],["Date of birth",p.dateOfBirth],["Phone",p.phone],["Email",p.email],["Address",p.address],["Emergency contact",p.emergencyContactName],["Emergency phone",p.emergencyContactPhone]]}/></section>
   {p.fullName&&<section className="border-b border-slate-200 py-6"><h2 className="mb-4 text-sm font-black uppercase">Live identity captures</h2><div className="grid grid-cols-3 gap-3">{[["selfie","Live selfie",data.hasSelfie],["id-front","ID front",data.hasIdFront],["id-back","ID back",data.hasIdBack]].map(([k,l,h]:any)=><div key={k} className="overflow-hidden rounded-xl border">{h?<img src={image(k)} className="aspect-[4/3] w-full object-cover"/>:<div className="grid aspect-[4/3] place-items-center text-xs text-slate-400">Not captured</div>}<div className="p-2 text-center text-xs font-bold">{l}</div></div>)}</div></section>}
   <section className="py-6"><h2 className="text-sm font-black uppercase">Owner review</h2><p className="mt-2 text-xs text-slate-500">Submitted: {data.submittedAt?new Date(data.submittedAt).toLocaleString("en-LK"):"—"} · Reviewed: {data.reviewedAt?new Date(data.reviewedAt).toLocaleString("en-LK"):"—"}</p><textarea rows={3} value={note} onChange={e=>setNote(e.target.value)} className="no-print mt-4 w-full rounded-xl border p-3" placeholder="Owner review note"/>{error&&<p className="mt-2 text-red-600">{error}</p>}{data.status==="submitted"&&<div className="no-print mt-4 flex gap-3"><button disabled={saving} onClick={()=>void decide("approved")} className="rounded-xl bg-emerald-600 px-5 py-2.5 font-bold text-white"><CheckCircle2 className="mr-2 inline" size={17}/>Approve</button><button disabled={saving} onClick={()=>void decide("rejected")} className="rounded-xl bg-red-600 px-5 py-2.5 font-bold text-white"><XCircle className="mr-2 inline" size={17}/>Reject</button></div>}</section>
   <footer className="border-t pt-3 text-[10px] text-slate-400">CONFIDENTIAL — encrypted staff identity data. Owner access only.</footer>
  </article>;
 return <div className="min-h-screen bg-slate-100 p-4">
  <div className="no-print mx-auto mb-4 flex max-w-[900px] justify-between"><button onClick={()=>setLocation("/admin/team-access")} className="rounded-xl bg-white px-4 py-2 font-bold"><ArrowLeft className="mr-2 inline" size={16}/>Team Access</button><button onClick={printA4} className="rounded-xl bg-slate-950 px-4 py-2 font-bold text-white"><Printer className="mr-2 inline" size={16}/>Print A4 report</button></div>
  {report}<A4PrintPortal active={printActive}>{report}</A4PrintPortal></div>
}
function Block({title,rows}:{title:string;rows:Array<[string,any]>}){return <div><h2 className="mb-3 text-sm font-black uppercase">{title}</h2><dl className="space-y-2">{rows.map(([l,v])=><div key={l}><dt className="text-[10px] font-bold uppercase text-slate-400">{l}</dt><dd className="whitespace-pre-wrap break-words text-sm font-semibold">{String(v||"—")}</dd></div>)}</dl></div>}
