import { useEffect,useMemo,useState } from "react";
import { useLocation,useParams } from "wouter";
import { ArrowLeft,Briefcase,BadgeCheck,CalendarCheck,FileText,GraduationCap,Languages,Loader2,Plus,Printer,Save,ShieldCheck,Trash2,UserRound } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { A4PrintPortal,useA4Print } from "@/components/A4PrintPortal";
import { useGetSettings } from "@workspace/api-client-react";
import { getBusinessName } from "@/lib/brand-settings";

const blank={personal:{displayName:"",preferredName:"",dateOfBirth:"",nationality:"Sri Lankan",nicPassport:"",personalEmail:"",phone:"",altPhone:"",address:""},employment:{employeeId:"",jobTitle:"",department:"",employmentType:"Full-time",joinedDate:"",workLocation:"",reportingTo:"",employmentStatus:"Active"},emergency:{name:"",relationship:"",phone:"",altPhone:""},cv:{headline:"",professionalSummary:"",careerObjective:"",skills:[] as string[],languages:[] as any[],education:[] as any[],experience:[] as any[],certifications:[] as any[],projects:[] as any[],references:[] as any[],links:{linkedin:"",portfolio:"",github:""},interests:[] as string[]}};
type Tab="overview"|"personal"|"employment"|"cv"|"verification";
const input="w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-pink-400";
const textarea=input+" resize-y";

export default function StaffProfile(){
 const{staffId}=useParams<{staffId:string}>();const id=Number(staffId),[,go]=useLocation(),{toast}=useToast();
 const {data:settings}=useGetSettings();const businessName=getBusinessName(settings);
 const[staff,setStaff]=useState<any>(null),[profile,setProfile]=useState<any>(blank),[verification,setVerification]=useState<any>(null),[tab,setTab]=useState<Tab>("overview"),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);const{active:printActive,print:printA4}=useA4Print();
 const req=async(url:string,options?:RequestInit)=>{const r=await fetch(url,{credentials:"include",cache:"no-store",...options,headers:options?.body?{"Content-Type":"application/json",...(options.headers||{})}:options?.headers});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||"Request failed");return b};
 const load=async()=>{setLoading(true);try{const[p,v]=await Promise.all([req(`/api/admin/staff/${id}/profile`),req(`/api/admin/staff/${id}/verification`).catch(()=>({exists:false}))]);setStaff(p.staff);const next=p.profile?mergeProfile(p.profile):structuredClone(blank);if(!p.profile&&v?.profile){next.personal.displayName=v.profile.fullName||p.staff?.name||"";next.personal.dateOfBirth=v.profile.dateOfBirth||"";next.personal.nicPassport=v.profile.nicNumber||"";next.personal.personalEmail=v.profile.email||"";next.personal.phone=v.profile.phone||"";next.personal.address=v.profile.address||"";next.emergency.name=v.profile.emergencyContactName||"";next.emergency.phone=v.profile.emergencyContactPhone||"";}setProfile(next);setVerification(v)}catch(e:any){toast({title:"Staff profile could not load",description:e.message,variant:"destructive"})}finally{setLoading(false)}};
 useEffect(()=>{void load()},[id]);
 const save=async()=>{setSaving(true);try{const b=await req(`/api/admin/staff/${id}/profile`,{method:"PUT",body:JSON.stringify(profile)});setProfile(mergeProfile(b.profile));toast({title:"Staff profile saved securely"})}catch(e:any){toast({title:"Could not save profile",description:e.message,variant:"destructive"})}finally{setSaving(false)}};
 const p=profile.personal,e=profile.employment,cv=profile.cv,em=profile.emergency;
 const name=p.displayName||staff?.name||"Staff member";const image=verification?.hasSelfie?`/api/admin/staff/${id}/verification/image/selfie?v=${encodeURIComponent(verification?.submittedAt||"")}`:"";
 const complete=useMemo(()=>{const fields=[p.displayName||staff?.name,p.phone,p.personalEmail,p.address,e.jobTitle,e.department,e.joinedDate,cv.professionalSummary,cv.skills?.length,cv.education?.length,cv.experience?.length];return Math.round(fields.filter(Boolean).length/fields.length*100)},[profile,staff]);
 if(loading)return <div className="grid min-h-[60vh] place-items-center"><Loader2 className="animate-spin text-pink-500"/></div>;
 if(!staff)return <div className="p-8 text-red-600">Staff account not found.</div>;
 return <div className="space-y-5">
  <div className="no-print flex flex-wrap items-center justify-between gap-3"><button onClick={()=>go("/admin/team-access")} className="flex items-center gap-2 rounded-xl border bg-white px-4 py-2 text-sm font-bold"><ArrowLeft size={16}/>Team Access</button><div className="flex gap-2"><button onClick={printA4} className="flex items-center gap-2 rounded-xl border bg-white px-4 py-2 text-sm font-bold"><Printer size={16}/>Print Professional CV</button><button disabled={saving} onClick={()=>void save()} className="flex items-center gap-2 rounded-xl bg-slate-950 px-5 py-2 text-sm font-black text-white">{saving?<Loader2 size={16} className="animate-spin"/>:<Save size={16}/>}Save Profile</button></div></div>
  <section className="no-print overflow-hidden rounded-3xl border bg-white shadow-sm"><div className="bg-gradient-to-r from-slate-950 via-indigo-950 to-slate-950 p-6 text-white"><div className="flex flex-wrap items-center gap-5">{image?<img src={image} className="h-24 w-24 rounded-3xl border-4 border-white/20 object-cover"/>:<div className="grid h-24 w-24 place-items-center rounded-3xl bg-white/10"><UserRound size={42}/></div>}<div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h1 className="text-3xl font-black">{name}</h1><span className={`rounded-full px-3 py-1 text-[10px] font-black uppercase ${verification?.status==="approved"?"bg-emerald-400/20 text-emerald-300":"bg-white/10 text-white/70"}`}>{verification?.status==="approved"?"Identity verified":"Verification "+(verification?.status||"not started")}</span></div><p className="mt-1 text-slate-300">{e.jobTitle||"Job title not added"}{e.department?` · ${e.department}`:""} · @{staff.username}</p><div className="mt-3 flex flex-wrap gap-2 text-[11px] text-white/70"><span>Employee ID: {e.employeeId||"—"}</span><span>•</span><span>{e.employmentType||"—"}</span><span>•</span><span>{e.employmentStatus||"Active"}</span></div></div><div className="rounded-2xl bg-white/10 px-5 py-3 text-center"><div className="text-2xl font-black">{complete}%</div><div className="text-[10px] uppercase text-white/60">Profile complete</div></div></div></div>
   <div className="flex overflow-x-auto border-b px-3">{([["overview","Overview"],["personal","Personal"],["employment","Employment"],["cv","CV / Resume"],["verification","Verification"]] as const).map(([k,l])=><button key={k} onClick={()=>setTab(k)} className={`shrink-0 border-b-2 px-4 py-3 text-xs font-black ${tab===k?"border-pink-500 text-pink-600":"border-transparent text-slate-500"}`}>{l}</button>)}</div>
   <div className="p-5 sm:p-6">
    {tab==="overview"&&<Overview staff={staff} p={p} e={e} cv={cv} verification={verification} setTab={setTab} go={go}/>}
    {tab==="personal"&&<div className="grid gap-5 lg:grid-cols-2"><Panel title="Personal & Contact"><div className="grid gap-3 sm:grid-cols-2"><F label="Full display name" value={p.displayName} onChange={v=>setProfile((x:any)=>({...x,personal:{...x.personal,displayName:v}}))}/><F label="Preferred name" value={p.preferredName} onChange={v=>setProfile((x:any)=>({...x,personal:{...x.personal,preferredName:v}}))}/><F label="Date of birth" type="date" value={p.dateOfBirth} onChange={v=>setProfile((x:any)=>({...x,personal:{...x.personal,dateOfBirth:v}}))}/><F label="Nationality" value={p.nationality} onChange={v=>setProfile((x:any)=>({...x,personal:{...x.personal,nationality:v}}))}/><F label="NIC / Passport" value={p.nicPassport} onChange={v=>setProfile((x:any)=>({...x,personal:{...x.personal,nicPassport:v}}))}/><F label="Personal email" type="email" value={p.personalEmail} onChange={v=>setProfile((x:any)=>({...x,personal:{...x.personal,personalEmail:v}}))}/><F label="Phone" value={p.phone} onChange={v=>setProfile((x:any)=>({...x,personal:{...x.personal,phone:v}}))}/><F label="Alternative phone" value={p.altPhone} onChange={v=>setProfile((x:any)=>({...x,personal:{...x.personal,altPhone:v}}))}/><label className="sm:col-span-2 text-xs font-bold text-slate-600">Address<textarea rows={3} className={textarea+" mt-1"} value={p.address} onChange={z=>setProfile((x:any)=>({...x,personal:{...x.personal,address:z.target.value}}))}/></label></div></Panel><Panel title="Emergency Contact"><div className="grid gap-3 sm:grid-cols-2"><F label="Contact name" value={em.name} onChange={v=>setProfile((x:any)=>({...x,emergency:{...x.emergency,name:v}}))}/><F label="Relationship" value={em.relationship} onChange={v=>setProfile((x:any)=>({...x,emergency:{...x.emergency,relationship:v}}))}/><F label="Phone" value={em.phone} onChange={v=>setProfile((x:any)=>({...x,emergency:{...x.emergency,phone:v}}))}/><F label="Alternative phone" value={em.altPhone} onChange={v=>setProfile((x:any)=>({...x,emergency:{...x.emergency,altPhone:v}}))}/></div><div className="mt-4 rounded-xl bg-amber-50 p-3 text-xs text-amber-700">Identity verification details remain in the separate encrypted verification record; this profile does not replace verification evidence.</div></Panel></div>}
    {tab==="employment"&&<Panel title="Employment Information"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><F label="Employee ID" value={e.employeeId} onChange={v=>emp(setProfile,"employeeId",v)}/><F label="Job title / Position" value={e.jobTitle} onChange={v=>emp(setProfile,"jobTitle",v)}/><F label="Department" value={e.department} onChange={v=>emp(setProfile,"department",v)}/><Select label="Employment type" value={e.employmentType} values={["Full-time","Part-time","Contract","Intern","Temporary"]} onChange={v=>emp(setProfile,"employmentType",v)}/><F label="Joined date" type="date" value={e.joinedDate} onChange={v=>emp(setProfile,"joinedDate",v)}/><F label="Work location" value={e.workLocation} onChange={v=>emp(setProfile,"workLocation",v)}/><F label="Reporting to" value={e.reportingTo} onChange={v=>emp(setProfile,"reportingTo",v)}/><Select label="Employment status" value={e.employmentStatus} values={["Active","Probation","On leave","Suspended","Resigned","Terminated"]} onChange={v=>emp(setProfile,"employmentStatus",v)}/></div></Panel>}
    {tab==="cv"&&<CvEditor profile={profile} setProfile={setProfile}/>}
    {tab==="verification"&&<div className="grid gap-4 lg:grid-cols-2"><Panel title="Identity Verification"><div className="flex items-center gap-3"><ShieldCheck className={verification?.status==="approved"?"text-emerald-600":"text-amber-500"} size={30}/><div><div className="font-black capitalize">{verification?.status||"Not started"}</div><div className="text-xs text-slate-500">{verification?.submittedAt?`Submitted ${new Date(verification.submittedAt).toLocaleString("en-LK")}`:"No identity submission yet"}</div></div></div>{verification?.profile&&<dl className="mt-4 space-y-2 text-sm"><Row l="Verified legal name" v={verification.profile.fullName}/><Row l="NIC / ID" v={verification.profile.nicNumber}/><Row l="Date of birth" v={verification.profile.dateOfBirth}/><Row l="Phone" v={verification.profile.phone}/><Row l="Email" v={verification.profile.email}/><Row l="Address" v={verification.profile.address}/><Row l="Emergency contact" v={verification.profile.emergencyContactName}/><Row l="Emergency phone" v={verification.profile.emergencyContactPhone}/></dl>}{verification?.exists&&<button onClick={()=>go(`/admin/staff-verification/${id}`)} className="mt-4 w-full rounded-xl bg-indigo-600 py-2.5 text-sm font-bold text-white">Open secure verification report & ID captures</button>}</Panel><Panel title="Attendance & Account"><dl className="space-y-2 text-sm"><Row l="Username" v={"@"+staff.username}/><Row l="Account" v={staff.active?"Active":"Paused"}/><Row l="Last login" v={staff.last_login_at?new Date(staff.last_login_at).toLocaleString("en-LK"):"Never"}/><Row l="Permissions" v={(staff.permissions||[]).join(", ")||"None"}/></dl><button onClick={()=>go("/admin/attendance")} className="mt-4 w-full rounded-xl border py-2.5 text-sm font-bold">Open attendance calendar</button></Panel></div>}
   </div>
  </section>
  <A4PrintPortal active={printActive}><CvPrint staff={staff} p={p} e={e} cv={cv} businessName={businessName}/></A4PrintPortal>
 </div>
}

function mergeProfile(x:any){return{personal:{...blank.personal,...x.personal},employment:{...blank.employment,...x.employment},emergency:{...blank.emergency,...x.emergency},cv:{...blank.cv,...x.cv,links:{...blank.cv.links,...x.cv?.links},skills:x.cv?.skills||[],languages:x.cv?.languages||[],education:x.cv?.education||[],experience:x.cv?.experience||[],certifications:x.cv?.certifications||[],projects:x.cv?.projects||[],references:x.cv?.references||[],interests:x.cv?.interests||[]}}}
function emp(set:any,key:string,value:string){set((x:any)=>({...x,employment:{...x.employment,[key]:value}}))}
function F({label,value,onChange,type="text"}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label className="text-xs font-bold text-slate-600">{label}<input type={type} className={input+" mt-1"} value={value||""} onChange={e=>onChange(e.target.value)}/></label>}
function Select({label,value,values,onChange}:{label:string;value:string;values:string[];onChange:(v:string)=>void}){return <label className="text-xs font-bold text-slate-600">{label}<select className={input+" mt-1"} value={value} onChange={e=>onChange(e.target.value)}>{values.map(v=><option key={v}>{v}</option>)}</select></label>}
function Panel({title,children}:{title:string;children:any}){return <section className="rounded-2xl border border-slate-200 bg-slate-50/60 p-4"><h2 className="mb-4 text-sm font-black uppercase tracking-wide text-slate-700">{title}</h2>{children}</section>}
function Row({l,v}:{l:string;v:any}){return <div className="flex justify-between gap-4 border-b border-slate-100 pb-2"><dt className="text-slate-400">{l}</dt><dd className="text-right font-bold text-slate-800">{String(v||"—")}</dd></div>}

function Overview({staff,p,e,cv,verification,setTab,go}:any){return <div className="grid gap-4 lg:grid-cols-3"><div className="lg:col-span-2 grid gap-4 sm:grid-cols-2"><Mini icon={<Briefcase/>} title="Employment" value={e.jobTitle||"Position not added"} sub={[e.department,e.employmentType].filter(Boolean).join(" · ")}/><Mini icon={<BadgeCheck/>} title="Identity" value={(verification?.status||"Not started").toUpperCase()} sub={verification?.status==="approved"?"Owner approved":"Secure verification required"}/><Mini icon={<FileText/>} title="Professional CV" value={cv.headline||"CV not completed"} sub={`${cv.education?.length||0} education · ${cv.experience?.length||0} experience`}/><Mini icon={<CalendarCheck/>} title="Account" value={staff.active?"Active staff account":"Account paused"} sub={staff.last_login_at?`Last login ${new Date(staff.last_login_at).toLocaleDateString("en-LK")}`:"Never logged in"}/></div><Panel title="Quick actions"><div className="space-y-2"><button onClick={()=>setTab("cv")} className="w-full rounded-xl bg-slate-950 px-3 py-2.5 text-sm font-bold text-white">Fill / Edit CV</button><button onClick={()=>setTab("verification")} className="w-full rounded-xl border bg-white px-3 py-2.5 text-sm font-bold">Verification & Access</button><button onClick={()=>go("/admin/attendance")} className="w-full rounded-xl border bg-white px-3 py-2.5 text-sm font-bold">Attendance Calendar</button></div></Panel></div>}
function Mini({icon,title,value,sub}:any){return <div className="rounded-2xl border bg-white p-4"><div className="flex items-center gap-2 text-xs font-black uppercase text-slate-400"><span className="text-pink-500">{icon}</span>{title}</div><div className="mt-3 font-black text-slate-900">{value}</div><div className="mt-1 text-xs text-slate-500">{sub||"—"}</div></div>}

function CvEditor({profile,setProfile}:any){const cv=profile.cv;const set=(k:string,v:any)=>setProfile((x:any)=>({...x,cv:{...x.cv,[k]:v}}));const arr=(k:string)=>cv[k]||[];const add=(k:string,row:any)=>set(k,[...arr(k),row]);const upd=(k:string,i:number,key:string,v:any)=>set(k,arr(k).map((x:any,n:number)=>n===i?{...x,[key]:v}:x));const del=(k:string,i:number)=>set(k,arr(k).filter((_:any,n:number)=>n!==i));return <div className="space-y-5"><Panel title="Professional Profile"><div className="grid gap-3"><F label="Professional headline" value={cv.headline} onChange={v=>set("headline",v)}/><label className="text-xs font-bold text-slate-600">Professional summary<textarea rows={5} className={textarea+" mt-1"} value={cv.professionalSummary} onChange={e=>set("professionalSummary",e.target.value)}/></label><label className="text-xs font-bold text-slate-600">Career objective<textarea rows={3} className={textarea+" mt-1"} value={cv.careerObjective} onChange={e=>set("careerObjective",e.target.value)}/></label><F label="Skills (comma separated)" value={(cv.skills||[]).join(", ")} onChange={v=>set("skills",v.split(",").map(x=>x.trim()).filter(Boolean))}/><F label="Interests (comma separated)" value={(cv.interests||[]).join(", ")} onChange={v=>set("interests",v.split(",").map(x=>x.trim()).filter(Boolean))}/></div></Panel>
 <ArraySection icon={<Briefcase/>} title="Work Experience" onAdd={()=>add("experience",{jobTitle:"",company:"",location:"",startDate:"",endDate:"",current:false,description:""})}>{arr("experience").map((x:any,i:number)=><Card key={i} onDelete={()=>del("experience",i)}><div className="grid gap-3 sm:grid-cols-2"><F label="Job title" value={x.jobTitle} onChange={v=>upd("experience",i,"jobTitle",v)}/><F label="Company" value={x.company} onChange={v=>upd("experience",i,"company",v)}/><F label="Location" value={x.location} onChange={v=>upd("experience",i,"location",v)}/><F label="Start date" type="month" value={x.startDate} onChange={v=>upd("experience",i,"startDate",v)}/><F label="End date" type="month" value={x.endDate} onChange={v=>upd("experience",i,"endDate",v)}/><label className="flex items-center gap-2 text-xs font-bold"><input type="checkbox" checked={!!x.current} onChange={e=>upd("experience",i,"current",e.target.checked)}/>Currently working here</label><label className="sm:col-span-2 text-xs font-bold">Responsibilities / achievements<textarea className={textarea+" mt-1"} rows={3} value={x.description} onChange={e=>upd("experience",i,"description",e.target.value)}/></label></div></Card>)}</ArraySection>
 <ArraySection icon={<GraduationCap/>} title="Education" onAdd={()=>add("education",{qualification:"",institution:"",field:"",startDate:"",endDate:"",grade:"",description:""})}>{arr("education").map((x:any,i:number)=><Card key={i} onDelete={()=>del("education",i)}><div className="grid gap-3 sm:grid-cols-2"><F label="Qualification" value={x.qualification} onChange={v=>upd("education",i,"qualification",v)}/><F label="Institution" value={x.institution} onChange={v=>upd("education",i,"institution",v)}/><F label="Field of study" value={x.field} onChange={v=>upd("education",i,"field",v)}/><F label="Grade / Result" value={x.grade} onChange={v=>upd("education",i,"grade",v)}/><F label="Start" type="month" value={x.startDate} onChange={v=>upd("education",i,"startDate",v)}/><F label="End" type="month" value={x.endDate} onChange={v=>upd("education",i,"endDate",v)}/><label className="sm:col-span-2 text-xs font-bold">Details<textarea className={textarea+" mt-1"} rows={2} value={x.description} onChange={e=>upd("education",i,"description",e.target.value)}/></label></div></Card>)}</ArraySection>
 <ArraySection icon={<Languages/>} title="Languages" onAdd={()=>add("languages",{language:"",level:""})}>{arr("languages").map((x:any,i:number)=><Card key={i} onDelete={()=>del("languages",i)}><div className="grid gap-3 sm:grid-cols-2"><F label="Language" value={x.language} onChange={v=>upd("languages",i,"language",v)}/><Select label="Proficiency" value={x.level||"Professional"} values={["Native","Fluent","Professional","Intermediate","Basic"]} onChange={v=>upd("languages",i,"level",v)}/></div></Card>)}</ArraySection>
 <ArraySection title="Certifications & Training" onAdd={()=>add("certifications",{name:"",issuer:"",date:"",credentialId:""})}>{arr("certifications").map((x:any,i:number)=><Card key={i} onDelete={()=>del("certifications",i)}><div className="grid gap-3 sm:grid-cols-2"><F label="Certification / Course" value={x.name} onChange={v=>upd("certifications",i,"name",v)}/><F label="Issuer" value={x.issuer} onChange={v=>upd("certifications",i,"issuer",v)}/><F label="Date" type="month" value={x.date} onChange={v=>upd("certifications",i,"date",v)}/><F label="Credential ID" value={x.credentialId} onChange={v=>upd("certifications",i,"credentialId",v)}/></div></Card>)}</ArraySection>
 <ArraySection title="Projects / Portfolio Work" onAdd={()=>add("projects",{name:"",role:"",description:"",link:""})}>{arr("projects").map((x:any,i:number)=><Card key={i} onDelete={()=>del("projects",i)}><div className="grid gap-3 sm:grid-cols-2"><F label="Project" value={x.name} onChange={v=>upd("projects",i,"name",v)}/><F label="Role" value={x.role} onChange={v=>upd("projects",i,"role",v)}/><F label="Link" value={x.link} onChange={v=>upd("projects",i,"link",v)}/><label className="sm:col-span-2 text-xs font-bold">Description<textarea className={textarea+" mt-1"} rows={2} value={x.description} onChange={e=>upd("projects",i,"description",e.target.value)}/></label></div></Card>)}</ArraySection>
 <ArraySection title="Professional References" onAdd={()=>add("references",{name:"",position:"",company:"",phone:"",email:""})}>{arr("references").map((x:any,i:number)=><Card key={i} onDelete={()=>del("references",i)}><div className="grid gap-3 sm:grid-cols-2"><F label="Name" value={x.name} onChange={v=>upd("references",i,"name",v)}/><F label="Position" value={x.position} onChange={v=>upd("references",i,"position",v)}/><F label="Company" value={x.company} onChange={v=>upd("references",i,"company",v)}/><F label="Phone" value={x.phone} onChange={v=>upd("references",i,"phone",v)}/><F label="Email" value={x.email} onChange={v=>upd("references",i,"email",v)}/></div></Card>)}</ArraySection>
 <Panel title="Professional Links"><div className="grid gap-3 sm:grid-cols-3"><F label="LinkedIn" value={cv.links?.linkedin||""} onChange={v=>set("links",{...cv.links,linkedin:v})}/><F label="Portfolio / Website" value={cv.links?.portfolio||""} onChange={v=>set("links",{...cv.links,portfolio:v})}/><F label="GitHub" value={cv.links?.github||""} onChange={v=>set("links",{...cv.links,github:v})}/></div></Panel>
 </div>}
function ArraySection({title,icon,onAdd,children}:any){return <section className="rounded-2xl border p-4"><div className="mb-3 flex items-center justify-between"><h2 className="flex items-center gap-2 text-sm font-black uppercase text-slate-700">{icon}{title}</h2><button onClick={onAdd} className="flex items-center gap-1 rounded-lg bg-pink-50 px-3 py-2 text-xs font-bold text-pink-700"><Plus size={13}/>Add</button></div><div className="space-y-3">{children}</div></section>}
function Card({children,onDelete}:any){return <div className="relative rounded-xl border bg-slate-50 p-3 pt-10"><button onClick={onDelete} className="absolute right-3 top-3 text-red-500"><Trash2 size={15}/></button>{children}</div>}

function CvPrint({staff,p,e,cv,businessName}:any){return <article className="staff-cv-print pb-print-flow bg-white font-sans text-slate-900"><header className="border-b-4 border-slate-950 pb-5"><h1 className="text-4xl font-black">{p.displayName||staff.name}</h1><p className="mt-1 text-lg font-bold text-pink-600">{cv.headline||e.jobTitle||"Professional Profile"}</p><p className="mt-2 text-xs text-slate-600">{[p.phone,p.personalEmail,p.address].filter(Boolean).join(" · ")}</p><p className="mt-1 text-[10px] text-slate-400">{[cv.links?.linkedin,cv.links?.portfolio,cv.links?.github].filter(Boolean).join(" · ")}</p></header>{cv.professionalSummary&&<CvSec title="Professional Summary"><p>{cv.professionalSummary}</p></CvSec>}{cv.careerObjective&&<CvSec title="Career Objective"><p>{cv.careerObjective}</p></CvSec>}{cv.experience?.length>0&&<CvSec title="Professional Experience">{cv.experience.map((x:any,i:number)=><div key={i} className="mb-3"><div className="flex justify-between gap-3"><b>{x.jobTitle} · {x.company}</b><span className="text-xs">{x.startDate} — {x.current?"Present":x.endDate}</span></div><div className="text-xs text-slate-500">{x.location}</div><p className="mt-1 whitespace-pre-wrap">{x.description}</p></div>)}</CvSec>}{cv.education?.length>0&&<CvSec title="Education">{cv.education.map((x:any,i:number)=><div key={i} className="mb-2"><b>{x.qualification}</b> · {x.institution}<div className="text-xs text-slate-500">{[x.field,x.grade,x.startDate&&x.endDate?`${x.startDate} — ${x.endDate}`:""].filter(Boolean).join(" · ")}</div></div>)}</CvSec>}<div className="grid grid-cols-2 gap-5">{cv.skills?.length>0&&<CvSec title="Key Skills"><p>{cv.skills.join(" · ")}</p></CvSec>}{cv.languages?.length>0&&<CvSec title="Languages"><p>{cv.languages.map((x:any)=>`${x.language} (${x.level})`).join(" · ")}</p></CvSec>}</div>{cv.certifications?.length>0&&<CvSec title="Certifications">{cv.certifications.map((x:any,i:number)=><div key={i}><b>{x.name}</b> · {x.issuer} {x.date&&`· ${x.date}`}</div>)}</CvSec>}{cv.projects?.length>0&&<CvSec title="Selected Projects">{cv.projects.map((x:any,i:number)=><div key={i} className="mb-2"><b>{x.name}</b>{x.role&&` · ${x.role}`}<p className="whitespace-pre-wrap">{x.description}</p></div>)}</CvSec>}{cv.references?.length>0&&<CvSec title="References"><div className="grid grid-cols-2 gap-4">{cv.references.map((x:any,i:number)=><div key={i}><b>{x.name}</b><div>{[x.position,x.company].filter(Boolean).join(" · ")}</div><div className="text-xs">{[x.phone,x.email].filter(Boolean).join(" · ")}</div></div>)}</div></CvSec>}<footer className="mt-8 border-t pt-2 text-[9px] text-slate-400">Professional CV generated from {businessName || "the configured business"} secure staff profile.</footer></article>}
function CvSec({title,children}:any){return <section className="mt-5 break-inside-avoid"><h2 className="mb-2 border-b pb-1 text-xs font-black uppercase tracking-[.16em] text-slate-500">{title}</h2><div className="text-sm leading-6">{children}</div></section>}
