import { useEffect, useState } from "react";
import { Activity, CheckCircle2, KeyRound, Loader2, Plus, Save, ShieldCheck, Trash2, UserCog, X } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

const PERMISSIONS = [
  ["dashboard","Dashboard","Daily overview"],
  ["orders","Orders","Create and update orders"],
  ["customers","Customers & Projects","Client and CRM details"],
  ["invoices","Invoices & Payments","Create invoices and mark payments"],
  ["shipping","Shipping Labels","Manage delivery details and labels"],
  ["catalog","Catalog Tools","Services and calculators"],
  ["products_view","Products","View product details only (Owner edits)"],
  ["price_lists_view","Private Price Lists","View lists and copy customer links (no editing)"],
  ["inventory","Inventory","View stock quantity without cost or supplier details"],
  ["production","Production Usage","Record papers/materials used and wasted"],
  ["website","Website Content","Edit pages, messages, reviews and notices"],
  ["finance","Finance & Costs","Sensitive: cash flow, expenses and cost values"],
  ["reports","Business Reports","Sensitive: revenue and performance reports"],
] as const;

type Staff = { id:number; name:string; username:string; permissions:string[]; active:boolean; created_at:string; last_login_at?:string };
type Log = { id:number; actor_username:string; action:string; path:string; status_code:number; created_at:string };
type DeleteRequest={id:number;target_type:string;target_id:string;target_label:string;reason?:string;status:"pending"|"approved"|"rejected";requested_by_name?:string;created_at:string};
const empty = { name:"", username:"", password:"", permissions:["orders","customers","invoices","shipping","products_view","price_lists_view","inventory","production"] as string[] };

export default function TeamAccess() {
  const { toast } = useToast();
  const [staff,setStaff]=useState<Staff[]>([]);
  const [logs,setLogs]=useState<Log[]>([]);
  const [deleteRequests,setDeleteRequests]=useState<DeleteRequest[]>([]);
  const [form,setForm]=useState(empty);
  const [editing,setEditing]=useState<Staff|null>(null);
  const [resetting,setResetting]=useState<Staff|null>(null);
  const [newPassword,setNewPassword]=useState("");
  const [tab,setTab]=useState<"team"|"activity"|"deletions">("team");
  const [loading,setLoading]=useState(true);
  const [saving,setSaving]=useState(false);
  const [verification,setVerification]=useState<Record<number,any>>({});
  const [onboardingUrl,setOnboardingUrl]=useState("");

  const request=async(url:string,options?:RequestInit)=>{
    const res=await fetch(url,{credentials:"include",cache:"no-store",...options,headers:options?.body?{"Content-Type":"application/json",...(options.headers||{})}:options?.headers});
    const body=await res.json().catch(()=>({}));
    if(!res.ok) throw new Error(body.error||"Request failed");
    return body;
  };
  const load=async()=>{setLoading(true);try{const [people,activity,deletions]=await Promise.all([request("/api/admin/team"),request("/api/admin/activity?limit=150"),request("/api/admin/deletion-requests")]);setStaff(people);setLogs(activity);setDeleteRequests(deletions);
    const checks=await Promise.all((Array.isArray(people)?people:[]).map(async(p:Staff)=>[p.id,await request(`/api/admin/staff/${p.id}/verification`).catch(()=>({exists:false}))] as const));
    setVerification(Object.fromEntries(checks));}catch(e:any){toast({title:"Team access could not load",description:e.message,variant:"destructive"});}finally{setLoading(false);}};
  useEffect(()=>{load();},[]);

  const toggle=(key:string,edit=false)=>{
    if(editing&&edit){setEditing({...editing,permissions:editing.permissions.includes(key)?editing.permissions.filter(p=>p!==key):[...editing.permissions,key]});}
    else setForm(f=>({...f,permissions:f.permissions.includes(key)?f.permissions.filter(p=>p!==key):[...f.permissions,key]}));
  };
  const create=async()=>{setSaving(true);try{const person=await request("/api/admin/team",{method:"POST",body:JSON.stringify(form)});const link=await request(`/api/admin/staff/${person.id}/verification-link`,{method:"POST",body:JSON.stringify({})});const full=window.location.origin+link.path;setOnboardingUrl(full);try{await navigator.clipboard.writeText(full);}catch{}toast({title:"Staff account & secure onboarding link created",description:"Verification link copied when browser permission allowed."});setForm(empty);await load();}catch(e:any){toast({title:"Could not create account",description:e.message,variant:"destructive"});}finally{setSaving(false);}};
  const update=async()=>{if(!editing)return;setSaving(true);try{await request(`/api/admin/team/${editing.id}`,{method:"PATCH",body:JSON.stringify(editing)});toast({title:"Staff access updated"});setEditing(null);await load();}catch(e:any){toast({title:"Could not update access",description:e.message,variant:"destructive"});}finally{setSaving(false);}};
  const createVerificationLink=async(person:Staff)=>{try{const link=await request(`/api/admin/staff/${person.id}/verification-link`,{method:"POST",body:JSON.stringify({})});const full=window.location.origin+link.path;setOnboardingUrl(full);try{await navigator.clipboard.writeText(full);}catch{}toast({title:"Secure onboarding link ready",description:"Link copied when browser permission allowed."});await load();}catch(e:any){toast({title:"Could not create verification link",description:e.message,variant:"destructive"});}};
  const resetPassword=async()=>{if(!resetting)return;setSaving(true);try{await request(`/api/admin/team/${resetting.id}/reset-password`,{method:"POST",body:JSON.stringify({password:newPassword})});toast({title:"Password reset successfully"});setResetting(null);setNewPassword("");}catch(e:any){toast({title:"Could not reset password",description:e.message,variant:"destructive"});}finally{setSaving(false);}};

  const decideDeletion=async(id:number,decision:"approved"|"rejected")=>{setSaving(true);try{await request(`/api/admin/deletion-requests/${id}/decision`,{method:"POST",body:JSON.stringify({decision})});toast({title:decision==="approved"?"Deletion approved":"Request rejected"});await load();}catch(e:any){toast({title:"Could not process request",description:e.message,variant:"destructive"});}finally{setSaving(false);}};

  const permissionGrid=(selected:string[],onToggle:(key:string)=>void)=><div className="grid gap-2 sm:grid-cols-2">{PERMISSIONS.map(([key,label,desc])=><label key={key} className={`flex cursor-pointer gap-3 rounded-2xl border p-3 transition ${selected.includes(key)?"border-pink-300 bg-pink-50":"border-gray-200 bg-white"}`}><input type="checkbox" checked={selected.includes(key)} onChange={()=>onToggle(key)} className="mt-1 accent-pink-500"/><span><span className="block text-sm font-bold text-gray-900">{label}</span><span className="text-[11px] text-gray-500">{desc}</span></span></label>)}</div>;

  return <div className="space-y-5">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><ShieldCheck className="text-pink-500"/><h1 className="text-2xl font-black">Team Access</h1></div><p className="mt-1 text-sm text-gray-500">Create separate staff logins and control exactly what each person can access.</p></div><div className="rounded-2xl border border-emerald-100 bg-emerald-50 px-4 py-2 text-xs font-bold text-emerald-700">Owner account always keeps full access</div></div>
    <div className="flex flex-wrap gap-1 rounded-2xl border bg-white p-1.5"><button onClick={()=>setTab("team")} className={`min-w-[140px] flex-1 rounded-xl py-2 text-sm font-bold ${tab==="team"?"bg-gray-900 text-white":"text-gray-500"}`}><UserCog size={15} className="mr-2 inline"/>Staff Accounts</button><button onClick={()=>setTab("deletions")} className={`min-w-[140px] flex-1 rounded-xl py-2 text-sm font-bold ${tab==="deletions"?"bg-gray-900 text-white":"text-gray-500"}`}><Trash2 size={15} className="mr-2 inline"/>Delete Requests {deleteRequests.filter(r=>r.status==="pending").length>0&&<span className="ml-1 rounded-full bg-rose-500 px-2 py-0.5 text-[10px] text-white">{deleteRequests.filter(r=>r.status==="pending").length}</span>}</button><button onClick={()=>setTab("activity")} className={`min-w-[140px] flex-1 rounded-xl py-2 text-sm font-bold ${tab==="activity"?"bg-gray-900 text-white":"text-gray-500"}`}><Activity size={15} className="mr-2 inline"/>Activity Log</button></div>
    {loading?<div className="flex justify-center py-24"><Loader2 className="animate-spin text-pink-500"/></div>:tab==="deletions"?<div className="overflow-hidden rounded-3xl border bg-white shadow-sm"><div className="border-b p-5"><h2 className="font-black">Deletion Approval Requests</h2><p className="text-xs text-gray-500">Records stay unchanged until you approve a staff request.</p></div><div className="divide-y">{deleteRequests.length?deleteRequests.map(item=><div key={item.id} className="grid gap-3 p-4 sm:grid-cols-[1fr_auto] sm:items-center"><div><div className="flex flex-wrap items-center gap-2"><b>{item.target_label}</b><span className="rounded-full bg-gray-100 px-2 py-1 text-[10px] font-black uppercase">{item.target_type.replace("_"," ")}</span><span className={`rounded-full px-2 py-1 text-[10px] font-black uppercase ${item.status==="pending"?"bg-amber-50 text-amber-600":item.status==="approved"?"bg-emerald-50 text-emerald-600":"bg-rose-50 text-rose-600"}`}>{item.status}</span></div><div className="mt-1 text-xs text-gray-500">Requested by {item.requested_by_name||"Staff"} · {new Date(item.created_at).toLocaleString("en-LK")}</div>{item.reason&&<div className="mt-2 rounded-xl bg-gray-50 p-2 text-xs text-gray-600">Reason: {item.reason}</div>}</div>{item.status==="pending"&&<div className="flex gap-2"><button disabled={saving} onClick={()=>decideDeletion(item.id,"rejected")} className="rounded-xl bg-rose-50 px-4 py-2 text-xs font-black text-rose-600">Reject</button><button disabled={saving} onClick={()=>decideDeletion(item.id,"approved")} className="flex items-center gap-1 rounded-xl bg-emerald-600 px-4 py-2 text-xs font-black text-white"><CheckCircle2 size={14}/>Approve & Delete</button></div>}</div>):<div className="py-16 text-center text-sm text-gray-400">No deletion requests</div>}</div></div>:tab==="activity"?<div className="overflow-hidden rounded-3xl border bg-white shadow-sm"><div className="border-b p-5"><h2 className="font-black">Recent Staff Changes</h2><p className="text-xs text-gray-500">Successful create, edit and delete actions are recorded automatically.</p></div><div className="divide-y">{logs.length?logs.map(log=><div key={log.id} className="grid gap-1 p-4 text-sm sm:grid-cols-[160px_1fr_180px]"><b>{log.actor_username}</b><span className="text-gray-700">{log.action}</span><span className="text-xs text-gray-400 sm:text-right">{new Date(log.created_at).toLocaleString("en-LK")}</span></div>):<div className="py-16 text-center text-sm text-gray-400">No staff activity yet</div>}</div></div>:<div className="grid gap-5 xl:grid-cols-[420px_1fr]">
      <div className="rounded-3xl border bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 text-lg font-black"><Plus size={18} className="text-pink-500"/>Add Staff Account</h2><div className="mt-4 space-y-3"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Staff name" className="input-field"/><input value={form.username} onChange={e=>setForm({...form,username:e.target.value})} placeholder="Login username" className="input-field"/><input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="Temporary password (10+ characters)" className="input-field"/><div><div className="mb-2 text-xs font-black uppercase text-gray-400">Allowed sections</div>{permissionGrid(form.permissions,key=>toggle(key))}</div><button onClick={create} disabled={saving||!form.name||form.username.length<3||form.password.length<10} className="flex w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-pink-500 to-purple-600 py-3 text-sm font-black text-white disabled:opacity-40">{saving?<Loader2 size={16} className="animate-spin"/>:<Plus size={16}/>}Create Staff Login</button></div></div>
      <div className="space-y-3">{staff.length?staff.map(person=><div key={person.id} className="rounded-3xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h3 className="font-black">{person.name}</h3><span className={`rounded-full px-2 py-0.5 text-[10px] font-black ${person.active?"bg-emerald-50 text-emerald-600":"bg-gray-100 text-gray-500"}`}>{person.active?"ACTIVE":"PAUSED"}</span></div><div className="text-xs text-gray-400">@{person.username} · Last login {person.last_login_at?new Date(person.last_login_at).toLocaleString("en-LK"):"Never"}</div></div><div className="flex flex-wrap gap-2"><button onClick={()=>window.location.href=`/admin/staff/${person.id}`} className="rounded-xl bg-pink-600 px-3 py-2 text-xs font-bold text-white"><UserCog size={13} className="mr-1 inline"/>Full Profile</button><button onClick={()=>setResetting(person)} className="rounded-xl border px-3 py-2 text-xs font-bold text-gray-600"><KeyRound size={13} className="mr-1 inline"/>Password</button><button onClick={()=>setEditing({...person,permissions:[...(person.permissions||[])]})} className="rounded-xl bg-gray-900 px-3 py-2 text-xs font-bold text-white">Manage Access</button></div></div><div className="mt-3 flex flex-wrap gap-1.5">{(person.permissions||[]).map(p=><span key={p} className="rounded-full bg-pink-50 px-2 py-1 text-[10px] font-bold text-pink-600">{PERMISSIONS.find(x=>x[0]===p)?.[1]||p}</span>)}</div><div className="mt-4 flex flex-wrap items-center gap-2 border-t pt-4"><span className={`rounded-full px-2.5 py-1 text-[10px] font-black uppercase ${verification[person.id]?.status==="approved"?"bg-emerald-100 text-emerald-700":verification[person.id]?.status==="submitted"?"bg-amber-100 text-amber-700":"bg-slate-100 text-slate-600"}`}>Identity: {verification[person.id]?.status||"not started"}</span>{verification[person.id]?.exists&&<button onClick={()=>window.open(`/admin/staff-verification/${person.id}`,"_blank")} className="rounded-lg border px-3 py-1.5 text-xs font-bold">Open secure report</button>}{!["submitted","approved"].includes(verification[person.id]?.status)&&<button onClick={()=>void createVerificationLink(person)} className="rounded-lg bg-indigo-50 px-3 py-1.5 text-xs font-bold text-indigo-700">Create onboarding link</button>}</div></div>):<div className="rounded-3xl border bg-white py-20 text-center text-sm text-gray-400">No staff accounts created yet</div>}</div>
    </div>}
    {onboardingUrl&&<div className="rounded-2xl border border-indigo-200 bg-indigo-50 p-4"><div className="text-xs font-black uppercase text-indigo-600">Secure staff onboarding link</div><div className="mt-2 flex gap-2"><input readOnly value={onboardingUrl} className="min-w-0 flex-1 rounded-xl border bg-white px-3 py-2 text-xs"/><button onClick={()=>{navigator.clipboard.writeText(onboardingUrl).catch(()=>{});toast({title:"Link copied"});}} className="rounded-xl bg-indigo-600 px-4 text-xs font-bold text-white">Copy</button><button onClick={()=>setOnboardingUrl("")} className="rounded-xl border bg-white px-3"><X size={14}/></button></div><p className="mt-2 text-[11px] text-indigo-700">Send only to this staff member. The link is for live selfie + ID front/back onboarding.</p></div>}
    {editing&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-gray-950/60 p-4 backdrop-blur-sm"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-xl font-black">Manage {editing.name}</h2><button onClick={()=>setEditing(null)}><X/></button></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><input value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})} className="input-field"/><input value={editing.username} onChange={e=>setEditing({...editing,username:e.target.value})} className="input-field"/></div><label className="my-4 flex items-center gap-2 rounded-xl bg-gray-50 p-3 text-sm font-bold"><input type="checkbox" checked={editing.active} onChange={e=>setEditing({...editing,active:e.target.checked})}/>Account active</label>{permissionGrid(editing.permissions,key=>toggle(key,true))}<button onClick={update} disabled={saving} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-gray-900 py-3 text-sm font-black text-white"><Save size={16}/>Save Access</button></div></div>}
    {resetting&&<div className="fixed inset-0 z-[110] flex items-center justify-center bg-gray-950/60 p-4"><div className="w-full max-w-md rounded-3xl bg-white p-6"><div className="flex justify-between"><h2 className="text-lg font-black">Reset {resetting.name}'s Password</h2><button onClick={()=>setResetting(null)}><X/></button></div><input type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)} placeholder="New password (10+ characters)" className="input-field mt-5"/><button onClick={resetPassword} disabled={saving||newPassword.length<10} className="mt-3 w-full rounded-xl bg-pink-600 py-3 text-sm font-black text-white disabled:opacity-40">Set New Password</button></div></div>}
  </div>;
}
