import { pgTable, serial, text, integer, real, timestamp } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

export const settingsTable = pgTable("settings", {
  id: serial("id").primaryKey(),
  businessName: text("business_name").notNull().default("PrintBloom"),
  tagline: text("tagline").notNull().default("Premium Printing & Graphic Design"),
  heroTitle: text("hero_title").notNull().default("Premium Printing for Every Vision"),
  heroSubtitle: text("hero_subtitle").notNull().default("From business cards to large banners, we bring your vision to life with precision and care."),
  whatsappNumber: text("whatsapp_number").notNull().default("94700000000"),
  whatsappMessage: text("whatsapp_message").notNull().default("Hi! I'd like to place an order with PrintBloom."),
  aboutStory: text("about_story").notNull().default("PrintBloom is your trusted printing partner, delivering high-quality prints for all your business and personal needs."),
  aboutMission: text("about_mission").notNull().default("Our mission is simple: to deliver exceptional prints on time, every time."),
  aboutImage: text("about_image"),
  ordersCompletedCount: integer("orders_completed_count").notNull().default(10),
  happyClientsPercent: integer("happy_clients_percent").notNull().default(99),
  starRating: real("star_rating").notNull().default(5.0),
  facebookUrl: text("facebook_url"),
  instagramUrl: text("instagram_url"),
  address: text("address"),
  email: text("email"),
  phone: text("phone"),
  website: text("website"),
  bankName: text("bank_name"),
  bankAccountHolder: text("bank_account_holder"),
  bankAccountNumber: text("bank_account_number"),
  bankBranch: text("bank_branch"),
  bankSwiftBic: text("bank_swift_bic"),
  paymentDueDays: integer("payment_due_days").notNull().default(7),
  overdueDays: integer("overdue_days").notNull().default(30),
  termsConditions: text("terms_conditions"),
  courierServices: text("courier_services").notNull().default("[]"),
  heroBgImage: text("hero_bg_image"),
  heroCtaText: text("hero_cta_text").notNull().default("Start Your Order"),
  heroCtaLink: text("hero_cta_link").notNull().default("/custom-project"),
  heroBadgeText: text("hero_badge_text").notNull().default("🌸 Premium Printing in Sri Lanka"),
  heroHighlightWord: text("hero_highlight_word").notNull().default("Vision"),
  aboutVision: text("about_vision"),
  aboutFoundedYear: text("about_founded_year").notNull().default("2020"),
  aboutTeamSize: text("about_team_size").notNull().default("10+"),
  aboutLocation: text("about_location").notNull().default("Sri Lanka"),
  privacyPolicy: text("privacy_policy"),
  termsOfService: text("terms_of_service"),
  seoTitle: text("seo_title").notNull().default("PrintBloom — Premium Printing & Graphic Design Sri Lanka"),
  seoDescription: text("seo_description").notNull().default("PrintBloom offers premium printing and graphic design services in Sri Lanka. Business cards, banners, labels, and more."),
  seoKeywords: text("seo_keywords").notNull().default("printing sri lanka, graphic design, business cards, banners, labels, printbloom"),
  seoOgImage: text("seo_og_image"),
  themePreset: text("theme_preset").notNull().default("pink-purple"),
  heroAvatarImage1: text("hero_avatar_image1"),
  heroAvatarImage2: text("hero_avatar_image2"),
  heroAvatarImage3: text("hero_avatar_image3"),
  heroAvatarImage4: text("hero_avatar_image4"),
  designerCredit: text("designer_credit").notNull().default("CODEARTIX"),
  ownerName: text("owner_name"),
  logoUrl: text("logo_url"),
  tiktokUrl: text("tiktok_url"),
  bankDetails: text("bank_details").notNull().default("[]"),
  courierCharge: text("courier_charge").notNull().default("450"),
  slPostCharge: text("sl_post_charge").notNull().default("250"),
  invoiceStandardRate: text("invoice_standard_rate").notNull().default("350"),
  invoiceExpressRate: text("invoice_express_rate").notNull().default("530"),
  invoiceWeightFirstKg: text("invoice_weight_first_kg").notNull().default("450"),
  invoiceWeightAddKg: text("invoice_weight_add_kg").notNull().default("200"),
  taglineEnabled: integer("tagline_enabled").notNull().default(1),
  showNameWithLogo: integer("show_name_with_logo").notNull().default(1),
  faviconUrl: text("favicon_url"),
  whatsappOrderTemplate: text("whatsapp_order_template").notNull().default("Hi {customerName}! 🌸\n\nThank you for choosing *PrintBloom*! Your order has been received and is being processed.\n\nOrder Number: *{orderNumber}*\n\nTrack your order status here:\n{trackingLink}\n\nIf you have any questions, feel free to contact us anytime.\n\nWarm regards,\n*PrintBloom* 🌸"),
  heroSlideImage1: text("hero_slide_image1"),
  heroSlideImage2: text("hero_slide_image2"),
  heroSlideImage3: text("hero_slide_image3"),
  heroSlideImage4: text("hero_slide_image4"),
  heroSlideImage5: text("hero_slide_image5"),
  homeFeatureCards: text("home_feature_cards").notNull().default("[]"),
  paymentQrUrl: text("payment_qr_url"),
  paymentButtonUrl: text("payment_button_url"),
  paymentButtonLabel: text("payment_button_label"),
  siteClosedEnabled: integer("site_closed_enabled").notNull().default(0),
  siteClosedMessage: text("site_closed_message").notNull().default("We are currently closed for maintenance. We will be back soon!"),
  ipayEnabled: integer("ipay_enabled").notNull().default(0),
  ipaySandbox: integer("ipay_sandbox").notNull().default(1),
  ipayToken: text("ipay_token"),
  ipaySecret: text("ipay_secret"),
  payButtonVisible: integer("pay_button_visible").notNull().default(1),
  googlePayEnabled: integer("google_pay_enabled").notNull().default(0),
  googlePayNumber: text("google_pay_number"),
  googlePayQrUrl: text("google_pay_qr_url"),
  googlePayInstructions: text("google_pay_instructions"),
  orderEmailNotificationsEnabled: integer("order_email_notifications_enabled").notNull().default(1),
  orderEmailRecipients: text("order_email_recipients").notNull().default(""),
  gmailUser: text("gmail_user"),
  gmailAppPassword: text("gmail_app_password"),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const insertSettingsSchema = createInsertSchema(settingsTable).omit({ id: true, updatedAt: true });
export type InsertSettings = z.infer<typeof insertSettingsSchema>;
export type Settings = typeof settingsTable.$inferSelect;

export const noticeTable = pgTable("notice", {
  id: serial("id").primaryKey(),
  enabled: integer("enabled").notNull().default(0),
  message: text("message").notNull().default(""),
  type: text("type").notNull().default("info"),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

/* ── Multiple notices (banners + popups) ─────────────────────────────────── */
export const noticesTable = pgTable("notices", {
  id: serial("id").primaryKey(),
  message: text("message").notNull().default(""),
  style: text("style").notNull().default("info"),
  placement: text("placement").notNull().default("banner"),
  enabled: integer("enabled").notNull().default(1),
  sortOrder: integer("sort_order").notNull().default(0),
  topic: text("topic"),
  imageUrl: text("image_url"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export type Notice = typeof noticesTable.$inferSelect;
export type InsertNotice = typeof noticesTable.$inferInsert;
